name: 'Update-Local-Group-DB'
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '07 04 * * 1'
defaults:
  run:
    shell: bash
jobs:
  Update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.DEPLOY_APP_ID }}
          private_key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
      - name: Install tools
        run: |
          sudo apt -y update
          sudo apt install -y libwww-curl-perl libjson-pp-perl perl-doc
      - name: Update the file
        run: |
          cd static/observations/localGroup
          ./localGroupSatellitesUpdate.pl ${{ secrets.NASA_ADS_API_TOKEN }}
          cd -
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "fix: update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "fix: update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update references in ${{ steps.depup.outputs.repo }} to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [Update-Local-Group-DB](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
          assignees: abensonca
          token: ${{ steps.generate-token.outputs.token }}
